CREATE TABLE IF NOT EXISTS brands
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS categories
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);


CREATE TABLE IF NOT EXISTS products
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT,
    description TEXT,
    brand_id    INT REFERENCES brands (id) ON DELETE SET NULL,
    category_id INT REFERENCES categories (id) ON DELETE SET NULL,
    price       NUMERIC
);



INSERT INTO brands (name) VALUES ('Apple'), ('Samsung'), ('Sony');

INSERT INTO categories (name) VALUES ('Smartphones'), ('Televisions'), ('Laptops');

INSERT INTO products (name, description, brand_id, category_id, price) VALUES
('iPhone 13', 'Latest Apple smartphone', 1, 1, 1000.00),
('Galaxy S21', 'Latest Samsung smartphone', 2, 1, 900.00),
('Bravia XR', 'Latest Sony television', 3, 2, 1500.00),
('MacBook Pro', 'Latest Apple laptop', 1, 3, 2000.00),
('VAIO Z', 'Latest Sony laptop', 3, 3, 1800.00);


